language: php
php:
- 7.1
- 7.2
- 7.3
addons:
  sonarcloud:
    organization: "dragonbe-github" # the key of the org you chose at step #3
    token:
      secure: FQCDqU91VA1n8jYrhHIC3SkDwZLHyek7satSFLXgmlM82mmNjoU4dYyiiNbFu9XP11DkUKYLttCFsb22qNPDPGywh90PEJD4Vz4G843ERacKgh0FK+8Q8sWrqs+Uj/3bcQlo3kK3CUyfUvCggjotr+vDbcf2cq3kdDW4VLFCtPY=

before_script:
- composer install --prefer-source --no-interaction
script:
- vendor/bin/phpunit
- vendor/bin/phpcs
- sonar-scanner
